### ISSUE TITLE
Address some of the PageSpeed Insights issues

### ISSUE THREAD

**Issue by tullo** [mraible/21-points#10]
Speed for mobile: 64/100
https://developers.google.com/speed/pagespeed/insights/?url=21-points.com

**Comment by mraible** [comment]
I'm not sure it can be optimized more. If you look at the [source](view-source:http://www.21-points.com/#/), you'll notice the CSS is at the top and the JS is at the bottom and everything is minified and concatenated. If you find a way to improve things, please send a PR!

**Comment by mraible** [comment]
After merging #11 and some additional fixes, we're now at 71/100.
<img width="636" alt="page-speed" src="https://cloud.githubusercontent.com/assets/17892/11377797/1fdbde34-92a5-11e5-8d47-73cf2d09df48.png">

**Comment by mraible** [comment]
After pull request #16, it seems we're still at 71/100.

**Comment by tullo** [comment]
Bummer. The score is 89 out of 100 on https://varvy.com/pagespeed/ though.
The display:none on the body element is not the right solution I'd guess.

**Comment by mraible** [comment]
In a previous version, you had commented out the CSS links and then re-activated them. In the current version, the CSS links are present. Did you mean to uncomment them?

**Comment by tullo** [comment]
I did not mean to uncomment them actually. Will add the change again.

**Comment by mraible** [comment]
Looks like it's up to a 71 now. Not sure if there's much more optimization possible without some sort of server-side rendering. One technique I've used in the past is to embed the JSON payload for the initial calls. Then modify the Angular services to look for a variable on window before making the server call.

**Comment by tullo** [comment]
Not sure if the embedding of JSON is gonna help as the complaints are regarding the extra network roundtrips for css rules necessary to render the above the fold content.

**Comment by tullo** [comment]
It's up to 98 now, but there is most likely no chance you'll like the current solution https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Ftullo-21points.herokuapp.com%2F&tab=mobile

**Comment by mraible** [comment]
Nice work! You're right about my admiration of the solution. ;)

**Comment by mraible** [comment]
I'm closing this until we can do some sort of server-rendering solution for the initial load.
