### ISSUE TITLE
The drinking thing..

### ISSUE THREAD

**Issue by tullo** [mraible/21-points#21]
This is probably just me and my lack of never having learnt a proper english.

If the ultimate target is to reach 21 points then I would have to enjoy a nice dark ale all 7 days in the week to get to the max of 7 x 3 points. Probably not the most healthy option ;-) and during summer time I would not mind.

Maybe it's just a matter of wording.
What about changing the question from "Did you drink?" to "No alcohol consumed?"?

Otherwise _not_ checking the checkbox "Did you drink?" should count as a _good_ thing and add to the total points.

**Comment by mraible** [comment]
I've noticed this and I agree the wording needs improvement. Maybe
"Responsible drinking?" or "Saving it for the weekend?" 😉

**Comment by tullo** [comment]
Agreed. "Responsible drinking?" will do. But with "Saving it for the weekend?" there is no chance to get 21 points :beers:
