### ISSUE TITLE
Token-based authentication doesn’t work with Spring WebSockets

### ISSUE THREAD

**Issue by schwella** [mraible/21-points#23]
The selected authentication mechanism and Spring WebSockets don't work well together as is stated in their documentation (https://jhipster.github.io/using_websockets.html).

On login I get an Access-Denied-Exeption for the websocket in the console.

The problem was discussed here:
https://github.com/jhipster/generator-jhipster/issues/1370

It seems to be fixed for OAuth2 as is stated there , but currently not for XAuth.

**Comment by mraible** [comment]
Closing because the latest version uses JWT authentication instead of XAuth.
