### ISSUE TITLE
How to enable ripple effect for the buttons?

### ISSUE THREAD

**Issue by ibgithub** [mraible/21-points#26]
After we add bootstrap-material-design the ripples.css and ripple.js are already included on the project, but still cannot make the buttons have ripple effect. How to enable ripple effect for the buttons?

**Comment by ibgithub** [comment]
I create simple html index using bootstrap-material-design and the ripple effect is exist, and then I compare with my application using jhipster, the different is: there is no div class="ripple-contaner" on jhipster component.
<img width="960" alt="17ripplenotok" src="https://cloud.githubusercontent.com/assets/364083/12167904/c63880a6-b4e3-11e5-8817-b0b975e1a0d7.png">

while on my simple index.html using bootstrap-material-design there is div class="ripple-contaner"
<img width="960" alt="16rippleok" src="https://cloud.githubusercontent.com/assets/364083/12167922/e4b1e9a0-b4e3-11e5-941d-aab444a66743.png">

**Comment by ibgithub** [comment]
I want to report to you that I already solved my problem with adding two files (css and js) from this link http://codepen.io/anon/pen/gPmJZR or http://codepen.io/zavoloklom/pen/Gubja (both are the same), I save it as ripples-alt.css and ripples.alt.js and I add class ripple-effect into my button or my menu, and now it's work, my button get ripple effect (I still don't know why it not working by default, may be it conflict with other component).

```
    <link rel="stylesheet" href="bower_components/bootstrap-material-design/dist/css/material.css" />
    <link rel="stylesheet" href="bower_components/bootstrap-material-design/dist/css/ripples.css" />
    <link rel="stylesheet" href="bower_components/bootstrap-material-design/dist/css/ripples-alt.css" />


    <script src="bower_components/bootstrap-material-design/dist/js/material.js"></script>
    <script src="bower_components/bootstrap-material-design/dist/js/ripples.js"></script>
    <script src="bower_components/bootstrap-material-design/dist/js/ripples-alt.js"></script>
```

and in my button I add:
class="btn btn-raised btn-primary ripple-effect"

**Comment by mraible** [comment]
I'm glad you figured out the problem. I'm closing this since I'm not concerned with adding this to 21-Points. 

NOTE: There is a JHipster module to install Bootstrap Material Design now. Not sure if this has the same issue: http://jhipster.github.io/modules/marketplace/#/details/generator-jhipster-bootstrap-material-design
