### ISSUE TITLE
Failed to sign in

### ISSUE THREAD

**Issue by jmmsegovia** [mraible/21-points#56]
Hello,
I’m not able to sign in. After the registration page, I click on the URL, then I input the correct password but always the same error message “Failed to sign in! Please check your credentials and try again.”
I had the same error trying to resetting the password.

BR

**Comment by mraible** [comment]
Does this happen when you download the project and run it locally or on www.21-points.com? If it happens on www.21-points.com, that's a [known issue](https://github.com/mraible/21-points/issues/50). If you keep trying, it'll eventually work. In the meantime, I've cleared out the auditing tables so you should be able to get past this issue.

**Comment by jmmsegovia** [comment]
Hello, sorry I didn't specify the environment. That was happening in www.21-points.com. Thanks

**Comment by ernsyn** [comment]
@mraible, can you reset the auditing table again? I tried to login more than 20 times; still failed.

**Comment by mraible** [comment]
@ernsyn Done!

**Comment by alfredorueda** [comment]
@mraible, can you reset the auditing table again? I tried to login many  times; still failed. Thanks!

**Comment by jonpemby** [comment]
I just signed up for a new account and I can't seem to sign in. 😢 

I've even tried typing my password in really slow but I can't seem to sign in. Is it the auditing table in my case or is it just me doing something really dumb? 😅

**Comment by mraible** [comment]
@alfredorueda and @jonpemby I reset the auditing tables, please try again.

**Comment by jonpemby** [comment]
@mraible sign in successful, thanks 👍

**Comment by alfredorueda** [comment]
It has been working for a week, but sorry, it is failing again. Thanks Matt!

**Comment by mraible** [comment]
I’m on vacation with no laptop to reset things. It’ll work if you try
enough times. For me, it sometimes takes 20-30 clicks.

**Comment by alfredorueda** [comment]
Ok! Thanks 😉

**Comment by renanfranca** [comment]
Hello i didn't receive the confirmation email. And I can't login. I used the email renan.andradefranca@gmail.com
