### ISSUE TITLE
questions about front end

### ISSUE THREAD

**Issue by dlaflamme** [mraible/21-points#75]
I have 2 questions:

1) Why is pointsListModification only broadcast from the PointsDeleteDialog component? Should it be broadcast elsewhere too? (for example in create() in PointsService)?

2) I am trying to understand how the content in home.component.html is shown when the application is accessed initially. I don't see a route for it in app-routing.module.ts and I don't see a jhi-home tag in any of the html templates.  How does this work?

**Comment by dlaflamme** [comment]
Answering question 2:

app.module.ts imports HomeModule from ./home/home.module.ts and then includes HomeModule in AppModule's imports.  HomeModule's import list, in turn, includes `RouterModule.forChild([HOME_ROUTE])` and HOME_ROUTE matches path: ''

One potential point of confusion is that while other modules do have routes that match path: '', they are all child routes. the HOME_ROUTE is the only on in the app that matches path: '' from the root.

**Comment by mraible** [comment]
Hello @dlaflamme,

I'm sorry for taking so long to respond, my life was kinda hectic in the last month. I'm not sure of the answer to your first question as I wrote this code quite a while ago. I did just test things and if you create a new points entity, it displays a message at the top, so the notification system seems to be working and my guess is it's simply not needed.

**Comment by mraible** [comment]
Closing due to lack of response. @dlaflamme If you still have questions, please reopen.
